version: '3.8'

services:
  gateway:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - alectrion-network
    ports:
      - 4000:4000
    command: bash -c "yarn && yarn dev"

networks:
  alectrion-network:
    external: true
